### ISSUE TITLE
Prefixfree is not part of the repo

### ISSUE THREAD

**Issue by lgarron** [LeaVerou/animatable#1]
I don't know if it should be, nor do I know much about things, like submodules, but I thought I'd note that "git clone" does not copy everything that's needed to run this locally (which makes tinkering a little harder).

**Comment by LeaVerou** [comment]
I know, CSSS has the same issue. I'm trying to come up with a sane way to solve it, without having to copy and paste files all the time. Submodules don't really help, as you have to include the whole repo in a folder, it's clumsy and awkward. I tried symlinks, but they don't work locally. Hard links break by every editor. Not sure what else to try.

**Comment by kizu** [comment]
Why not use just an absolute link to `http://leaverou.github.com/prefixfree/prefixfree.min.js`?

**Comment by LeaVerou** [comment]
It makes it super slow every time I use github links. I think they introduced a delay to stop people using their service as a CDN.

**Comment by LeaVerou** [comment]
For now, I settled with using the github link, so closing this. But I really hope I find a better solution in the future.
