### ISSUE TITLE
"Skew" example not working in Safari 5.1 Windows

### ISSUE THREAD

**Issue by daneden** [LeaVerou/animatable#12]
The "skew" example (25) doesn't work in Safari 5.1 Windows. Still working in Chrome, so clearly not a problem with the webkit declarations - it could be an issue related to prefixfree.

**Comment by LeaVerou** [comment]
From [this testcase](http://jsfiddle.net/leaverou/8VUNn/1/) it looks like it's a Safari bug. I'll report it to the Webkit team, as it's also reproducible in the nightlies (but strangely not in Chrome). 
Thanks!
