### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by Bilge** [LeaVerou/animatable#332]
From what I can tell, most assets are blocked by browser policy in both Firefox and Chrome.

![image](https://user-images.githubusercontent.com/470626/89944832-5ca71100-dc18-11ea-8d46-c274b4568ada.png)

**Comment by LeaVerou** [comment]
This issue seems to appear only on `https`, which was not enforced. Anyhow, it should be fixed now, and I turned on https enforcement.
