### ISSUE TITLE
GitHub Ribbon out of date

### ISSUE THREAD

**Issue by joeyespo** [LeaVerou/animatable#40]
The GitHub Ribbon isn't showing, probably because it's using a cached version of the image that no longer exists. Try using one of these image URLs instead.

https://github.com/blog/273-github-ribbons

**Comment by LeaVerou** [comment]
Thanks! I'll update it as soon as I get some free time (or when somebody sends a pull request _hint hint_ :p )

**Comment by joeyespo** [comment]
Fixed with #41.
