### ISSUE TITLE
transform value must have unit suffix

### ISSUE THREAD

**Issue by panayiotisa** [LeaVerou/animatable#5]
Not sure if this is a firefox or css3 requirement, probably the latter.

**Comment by panayiotisa** [comment]
Let me clarify, I'm referring to tranform/5 where the perspective() value does not have a unit suffix. I thought that this was the reason why firefox did not render the transform. However the issue remains even after I tried to manually correct it.

**Comment by panayiotisa** [comment]
Ok, after I edited the _generated_ style element (damn you prefixfree :) ) the suffixed unit did the magic for firefox.

**Comment by LeaVerou** [comment]
So you mean like `perspective(600px)`?

**Comment by panayiotisa** [comment]
Yes. The spec says it's number value, but [firefox expects a length value](http://mxr.mozilla.org/mozilla-central/source/layout/style/nsCSSParser.cpp#7463). I think firefox is right, we 're measuring distance.

**Comment by LeaVerou** [comment]
FWIW, I agree it should be a length. I don't like this recent trend of the spec using unitless values to mean pixels in a few places. 

Does it work in the other browsers with a unit?

**Comment by panayiotisa** [comment]
Chrome and Safari (both on windows) work fine.

**Comment by panayiotisa** [comment]
Absolutely fixed.

**Comment by LeaVerou** [comment]
Great, thanks for letting me know about this quirk!
